Add missing properties of User
nerdishbynature/octokit.swift pull request #114
Opened 2020-09-05 09:20 UTC by mvolpato

I added some properties that were missing in the `User` model.

I also added a `Plan` model, which can be returned when you retrieve a user.
As far as I know there is no direct API to request plans.

Tests added for `Plan` and on the unit test on the `user_me.json` file.

2020-09-05 10:18 UTC, MaxDesiatov approved these changes
Seems legit

2020-09-08 11:34 UTC, pietbrauer requested changes
Thanks a lot! Just some very minor things.

2020-09-08 11:34 UTC, pietbrauer commented on Tests/OctoKitTests/UserTests.swift
> +        XCTAssertNil(subject.bio)
Currently I am not sure if this is mapped correctly or if the field is empty in the JSON. Could you change the stub and add a `bio`, `twitterUsername` and `noteId`?

2020-09-08 11:34 UTC, pietbrauer commented on OctoKit/User.swift
> +    open var nodeId: String?
Could we also uppercase `Id`?

```suggestion
    open var nodeID: String?
```

2020-09-08 11:58 UTC, pietbrauer commented on Tests/OctoKitTests/Fixtures/user_me.json
> +    "bio": "Tweeting about iOS and Drumming",
Haha very humbled, wasn't aware it's my user in the stubs 😆

2020-09-10 07:52 UTC, pietbrauer approved these changes

2020-09-10 07:52 UTC, merged

2020-09-10 07:52 UTC, pietbrauer commented
Thanks again for your contribution!