Adding ability to create new pull request.
nerdishbynature/octokit.swift pull request #167
Opened 2023-05-08 19:03 UTC by ps2

These changes allow the creation of a new pull request using the Octokit package.

I tried following the existing code patterns as best I could. Let me know if you have any feedback. Thanks!

2023-05-08 19:25 UTC, pietbrauer requested changes
Thanks a lot! Please also add the async/await compatible version.

2023-05-08 19:25 UTC, pietbrauer commented on OctoKit/PullRequest.swift
> +//            func pullRequest(_ session: RequestKitURLSession = URLSession.shared,
This seems obsolete?

2023-05-08 19:25 UTC, pietbrauer commented on OctoKit/PullRequest.swift
> +                parameters["maintainer_can_modify"] = (mantainerCanModify ? "true" : "false")
Did you try to just put the swift bool here? Codable should be able to figure it out…

2023-05-08 19:25 UTC, pietbrauer commented on OctoKit/PullRequest.swift
> +                parameters["draft"] = (draft ? "true" : "false")
Same here. Just writing it like this should be sufficient.
```suggestion
                parameters["draft"] = draft
```

2023-05-08 19:25 UTC, pietbrauer commented on OctoKit/PullRequest.swift
> +                     head_repo: String? = nil,
Please stick to camel case

2023-05-08 19:25 UTC, pietbrauer commented on OctoKit/PullRequest.swift
> +     - parameter head_repo: The name of the repository where the changes in the pull request were made.
Please stick to camel case

2023-05-09 04:51 UTC, pietbrauer requested changes
Thanks for the changes! Something I totally forgot yesterday was that some tests would also be really nice.

2023-05-10 16:46 UTC, ps2 commented
Added tests, thanks!

2023-05-11 05:51 UTC, pietbrauer approved these changes

2023-05-11 05:52 UTC, pietbrauer commented on OctoKit/PullRequest.swift
> +            if let headRepo {
Tests are failing because in the swift version we support this shorthand is not available.

2023-05-21 06:50 UTC, pietbrauer submitted a review, later dismissed

2023-05-21 07:13 UTC, pietbrauer commented
@ps2 Linting is still failing sadly otherwise it's good to go.

2023-05-22 20:23 UTC, pietbrauer approved these changes

2023-05-23 04:40 UTC, merged